# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 0
#
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
#/gun/particle gamma
#/gun/energy 6 MeV
#
#/run/beamOn 5
# 
# proton 210 MeV to the direction (0.,0.,1.)
#
/gun/particle proton
#/gun/energy 6500 GeV
/gun/energy 100 GeV
#/tracking/verbose 2
/tracking/verbose 0
#
/run/beamOn 200
